import type { Metadata } from "next";
import "./globals.css";
import "../constants/Theme.css";
import Navbar from "@/components/sections/Navbar"; 
import Footer from "@/components/sections/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col relative scroll-smooth">
        <Navbar />
        <div
          className="w-full pointer-events-none transition-all duration-75"
          style={{
            height: "400px",
          }}
        /> 
        {children}
        <Footer/>
      </body>
    </html>
  );
}
